# Generated by Django 5.1.6 on 2025-02-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absent',
            name='response_content',
            field=models.TextField(blank=True),
        ),
    ]
